### ISSUE TITLE
Simplify main export?

### ISSUE THREAD

**Issue by ben-eb** [radiovisual/unicode-range-json#1]
Hi @radiovisual,

Thanks for the module! I'm just curious as to why you've wrapped the JSON file in a function when you can export it directly:

```js
module.exports = require('./unicode-ranges.json');
```

This makes the consuming code simpler:

```js
const ranges = require('unicode-range-json');
```

As opposed to:

```js
const ranges = require('unicode-range-json')();
```

I can send a pull request if you would like.

Thanks!

**Comment by radiovisual** [comment]
I think I originally planned to attach helper functions to this module, but then moved those to [unicode-range](https://www.npmjs.com/package/unicode-range), so the unnessesary function wrap was probably an artifact left behind. Pull request is welcome if you want to clean it up. Thanks!
